[versions]
android = "8.6.1"
kotlin = "2.0.20"

[libraries]
android-gradleApi = { group = "com.android.tools.build", name = "gradle-api", version.ref = "android" }

jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "24.1.0" }
jetbrains-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }

g000sha256-sonatypeMavenCentral = { id = "dev.g000sha256.sonatype-maven-central", version = "1.0.0" }

gmazzo-buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.0" }

jetbrains-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.16.3" }

jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }